<?php

namespace Amandine\ProjetBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
	/*public function getByDate(\Datetime $validatingDate)
	{
		 $from = new \DateTime($validatingDate->format("Y-m-d")." 00:00:00");
    $to   = new \DateTime($validatingDate->format("Y-m-d")." 23:59:59");

    $qb = $this->createQueryBuilder("e");
    $qb
        ->andWhere('e.date BETWEEN :from AND :to')
        ->setParameter('from', $from )
        ->setParameter('to', $to)
    ;
    $result = $qb->getQuery()->getResult();

    return $result;
	}*/
}
