<?php

namespace Amandine\ProjetBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function getCommentsForProduct($id)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.product = :id')
                   ->addOrderBy('c.createDate')
                   ->setParameter('id', $id);


        return $qb->getQuery()
                  ->getResult();
    }
}
