<?php

namespace Amandine\ProjetBundle\Repository;

/**
 * Liaison_basketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Liaison_basketRepository extends \Doctrine\ORM\EntityRepository
{
}
